const ItemData = [
    {
      id: 1,
      name: "top1",
      size: "",
      quantity: 0,
      tag: "top",
      img: "./images/top1.png",
    },
    {
      id: 2,
      name: "top2",
      size: "",
      quantity: 0,
      tag: "top",
      img: "./images/top2.png",
    },
    {
      id: 3,
      name: "top3",
      size: "",
      price: 0,
      quantity: 0,
      tag: "top",
      img: "./images/top3.png",
    },
    {
      id: 4,
      name: "top4",
      size: "",
      price: 0,
      quantity: 0,
      tag: "top",
      img: "./images/top4.png",
    },
    {
      id: 5,
      name: "top5",
      size: "",
      price: 0,
      quantity: 0,
      tag: "top",
      img: "./images/top5.png",
    },
    {
      id: 6,
      name: "top6",
      size: "",
      price: 0,
      quantity: 0,
      tag: "top",
      img: "./images/top6.png",
    },
    {
      id: 7,
      name: "top7",
      size: "",
      price: 0,
      quantity: 0,
      tag: "top",
      img: "./images/top7.png",
    },
    {
      id: 8,
      name: "top8",
      size: "",
      price: 0,
      quantity: 0,
      tag: "top",
      img: "./images/top8.png",
    },
    {
      id: 9,
      name: "top9",
      size: "",
      price: 0,
      quantity: 0,
      tag: "top",
      img: "./images/top9.png",
    },
    {
      id: 10,
      name: "top10",
      size: "",
      price: 0,
      quantity: 0,
      tag: "top",
      img: "./images/top10.png",
    },
    {
      id: 11,
      name: "top11",
      size: "",
      price: 0,
      quantity: 0,
      tag: "top",
      img: "./images/top11.png",
    },
    {
      id: 12,
      name: "bottom",
      size: "",
      price: 0,
      quantity: 0,
      tag: "bottom",
      img: "./images/bottom.png",
    },
    {
      id: 13,
      name: "acc1",
      size: "",
      price: 0,
      quantity: 0,
      tag: "acc",
      img: "./images/acc1.png",
    },
    {
      id: 14,
      name: "acc2",
      size: "",
      price: 0,
      quantity: 0,
      tag: "acc",
      img: "./images/acc2.png",
    },
    {
      id: 15,
      name: "acc3",
      size: "",
      price: 0,
      quantity: 0,
      tag: "acc",
      img: "./images/acc3.png",
    },
    {
      id: 16,
      name: "acc4",
      size: "",
      price: 0,
      quantity: 0,
      tag: "acc",
      img: "./images/acc4.png",
    },
  ]

  export default ItemData